// ──────────────────────────────────────────────────────────────────────────────
// Reference witness — key files.
//
// There is no default key. A key is generated by `keygen` (or by the deployer's
// own tooling) and named in the config. On load, a private key file that the
// group or others can access is refused: the receipts are only worth what the
// custody of this key is worth.
// ──────────────────────────────────────────────────────────────────────────────

import { createPrivateKey, createPublicKey, generateKeyPairSync } from "crypto";
import type { KeyObject } from "crypto";
import {
  chmodSync,
  closeSync,
  existsSync,
  fstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "fs";
import { join } from "path";

import { publicKeyFingerprint as fingerprintOfPem } from "../../../src/l0/fingerprint";
import { NotARegularFile, openRegularFile, readErrorText, readRegularFile } from "./regular-file";

export const PRIVATE_KEY_FILE = "witness.key";
export const PUBLIC_KEY_FILE = "witness.pub.pem";

export class KeyFileError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "KeyFileError";
  }
}

/**
 * The public key's fingerprint in ILAS's format (src/l0/fingerprint.ts):
 * "sha256:" + lowercase hex SHA-256 of its SPKI DER bytes. keygen, `fingerprint`,
 * `verify` and the STARTED line print it, and ILAS core reports a witness key
 * in it, so the node's copy of the key can be compared with the operator's.
 */
export function publicKeyFingerprint(publicKey: KeyObject): string {
  return fingerprintOfPem(publicKey.export({ type: "spki", format: "pem" }) as string);
}

export interface GeneratedKeyFiles {
  readonly privateKeyPath: string;
  readonly publicKeyPath: string;
  /** publicKeyFingerprint() of the public key written. */
  readonly fingerprint: string;
  /** The private key file's permission bits as read back after writing (always 0o600). */
  readonly privateKeyMode: number;
}

/** A mode as four octal digits, e.g. "0600". */
export function octalMode(mode: number): string {
  return (mode & 0o777).toString(8).padStart(4, "0");
}

function errorText(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/** Remove a key file this call created, and say whether that worked. */
function removedAgain(path: string): string {
  try {
    unlinkSync(path);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      return `It could not be removed again: delete ${path} yourself.`;
    }
  }
  return `The key file was removed again.`;
}

/**
 * Generate a fresh Ed25519 key pair into `outDir`: witness.key (PKCS#8 PEM,
 * mode 0600) and witness.pub.pem (SPKI PEM). Refuses to overwrite either file.
 *
 * The private key's mode is read back after it is set. On a file system that
 * does not keep POSIX permissions (a Windows drive under WSL mounted without
 * metadata, for example) it is not 0600, and on one that refuses chmod to this
 * account (a FAT or exFAT mount owned by another account) setting it throws.
 * Either way, and when writing the key fails, the key is removed again and
 * KeyFileError says why: a key there is readable beyond its owner, and
 * loadPrivateKeyFile() would refuse it anyway.
 */
export function generateKeyFiles(outDir: string): GeneratedKeyFiles {
  const privateKeyPath = join(outDir, PRIVATE_KEY_FILE);
  const publicKeyPath = join(outDir, PUBLIC_KEY_FILE);
  for (const path of [privateKeyPath, publicKeyPath]) {
    if (existsSync(path)) {
      throw new KeyFileError(
        `refusing to overwrite ${path}: a witness key that is replaced silently ` +
          `invalidates every receipt a node expects to verify. Move it aside first.`
      );
    }
  }
  mkdirSync(outDir, { recursive: true, mode: 0o700 });

  const { privateKey, publicKey } = generateKeyPairSync("ed25519");
  const privatePem = privateKey.export({ type: "pkcs8", format: "pem" }) as string;
  const publicPem = publicKey.export({ type: "spki", format: "pem" }) as string;

  // "wx": fail if the file appeared since the check above. That failure is the
  // one place nothing is removed: the file is not this call's. From here on,
  // every failure removes the key again before it is reported.
  const fd = openSync(privateKeyPath, "wx", 0o600);
  try {
    try {
      writeFileSync(fd, privatePem);
    } finally {
      closeSync(fd);
    }
  } catch (error) {
    throw new KeyFileError(
      `could not write ${privateKeyPath} (${errorText(error)}). ` + removedAgain(privateKeyPath)
    );
  }
  // The mode is set again explicitly because the creation mode is filtered by
  // the umask, and read back because some file systems do not keep it.
  let privateKeyMode: number | undefined;
  let chmodError: unknown;
  try {
    chmodSync(privateKeyPath, 0o600);
    privateKeyMode = statSync(privateKeyPath).mode & 0o777;
  } catch (error) {
    chmodError = error;
  }
  if (privateKeyMode !== 0o600) {
    throw new KeyFileError(
      (privateKeyMode === undefined
        ? `wrote ${privateKeyPath}, but setting its mode to 0600 failed ` +
          `(${errorText(chmodError)}): this file system does not let this account set ` +
          `POSIX permissions on it (for example a FAT or exFAT mount owned by another ` +
          `account), so the group or others may be able to read the key. `
        : `wrote ${privateKeyPath}, but its mode reads back as ${octalMode(privateKeyMode)}, ` +
          `not 0600, after it was set to 0600: this file system does not keep POSIX ` +
          `permissions (for example a Windows drive under WSL mounted without metadata), ` +
          `so the group or others may be able to read the key. `) +
        removedAgain(privateKeyPath) +
        ` Generate the key with --out on a POSIX file system.`
    );
  }
  try {
    writeFileSync(publicKeyPath, publicPem, { mode: 0o644, flag: "wx" });
  } catch (error) {
    // Do not leave a private key behind whose public half was never written.
    try {
      unlinkSync(privateKeyPath);
    } catch {
      // The original error is the one worth reporting.
    }
    throw error;
  }
  return {
    privateKeyPath,
    publicKeyPath,
    fingerprint: publicKeyFingerprint(publicKey),
    privateKeyMode,
  };
}

/**
 * Load an Ed25519 private key file, refusing one the group or others can access.
 * The permission check uses POSIX mode bits, read from the same open file
 * descriptor the key is read from. The file is opened without blocking and
 * refused unless it is a regular file: a FIFO there is refused at once, never
 * waited on (regular-file.ts).
 */
export function loadPrivateKeyFile(path: string): KeyObject {
  let fd: number;
  try {
    fd = openRegularFile(path);
  } catch (error) {
    if (error instanceof NotARegularFile) throw new KeyFileError(`private key path ${error.message}`);
    throw new KeyFileError(`cannot open private key file ${path}: ${String(error)}`);
  }
  try {
    const stats = fstatSync(fd);
    const mode = stats.mode & 0o777;
    if ((mode & 0o077) !== 0) {
      throw new KeyFileError(
        `refusing private key file ${path}: its mode is ${mode
          .toString(8)
          .padStart(4, "0")}, so the group or others can access it. Anyone who can ` +
          `read this key can sign receipts in the witness's name. Fix with: chmod 600 ${path}`
      );
    }
    let key: KeyObject;
    try {
      key = createPrivateKey(readFileSync(fd));
    } catch (error) {
      throw new KeyFileError(`cannot parse private key file ${path}: ${String(error)}`);
    }
    if (key.asymmetricKeyType !== "ed25519") {
      throw new KeyFileError(
        `private key file ${path} holds a ${String(key.asymmetricKeyType)} key; ` +
          `the witness signs with ed25519 only`
      );
    }
    return key;
  } finally {
    closeSync(fd);
  }
}

/**
 * True when `bytes` hold PRIVATE key material. createPublicKey() would quietly
 * derive the public half from it, so a private key handed over where the public
 * one belongs would be accepted; the caller refuses it instead.
 */
function holdsPrivateKey(bytes: Buffer): boolean {
  if (bytes.toString("latin1").includes("PRIVATE KEY")) return true;
  try {
    createPrivateKey(bytes);
    return true;
  } catch {
    return false;
  }
}

/**
 * Load an Ed25519 public key from a PEM file. A file that holds a PRIVATE key is
 * refused: whoever checks receipts is to be given the public key only. So is
 * anything that is not a regular file: it is opened without blocking, so a FIFO
 * is refused at once, never waited on (regular-file.ts).
 */
export function loadPublicKeyFile(path: string): KeyObject {
  let bytes: Buffer;
  try {
    bytes = readRegularFile(path);
  } catch (error) {
    throw new KeyFileError(`cannot read public key file ${path}: ${readErrorText(error)}`);
  }
  if (holdsPrivateKey(bytes)) {
    throw new KeyFileError(
      `${path} holds a PRIVATE key, not a public key. Give only the witness's ` +
        `PUBLIC key file (${PUBLIC_KEY_FILE}, as keygen writes it); the private key ` +
        `stays with the witness's operator and is never handed to anyone who checks receipts.`
    );
  }
  let key: KeyObject;
  try {
    key = createPublicKey(bytes);
  } catch (error) {
    throw new KeyFileError(`cannot read public key file ${path}: ${String(error)}`);
  }
  if (key.asymmetricKeyType !== "ed25519") {
    throw new KeyFileError(
      `public key file ${path} holds a ${String(key.asymmetricKeyType)} key, not ed25519`
    );
  }
  return key;
}
